package org.mnm.tools;

/**
 * Generated by gemini 3.1-pro
 */
class Crc64Redis {

    private static final long POLY = 0x95AC9329AC4BC9B5L; // Reflected 0xAD93D23594C935A9
    private static final long[] TABLE = new long[256];

    // Pre-compute the lookup table when the class is loaded
    static {
        for (int i = 0; i < 256; i++) {
            long crc = i;
            for (int j = 0; j < 8; j++) {
                if ((crc & 1) == 1) {
                    crc = (crc >>> 1) ^ POLY;
                } else {
                    crc >>>= 1;
                }
            }
            TABLE[i] = crc;
        }
    }

    private Crc64Redis() {
    }

    /**
     * Calculates the CRC-64-Redis checksum for a byte array.
     *
     * @param data The input data
     * @return The 64-bit CRC checksum
     */
    static long calculate(byte[] data) {
        long crc = 0x0000000000000000L; // Initial value

        for (byte b : data) {
            int lookupIndex = ((int) crc ^ b) & 0xFF;
            crc = (crc >>> 8) ^ TABLE[lookupIndex];
        }

        return crc; // No final XOR mask is applied in CRC-64-Redis
    }

    /**
     * Helper method to return the CRC as a 16-character hex string (like Redis does).
     */
    static String calculateHex(byte[] data) {
        long crc = calculate(data);
        return String.format("%016x", crc);
    }

}